<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive Surgical Table</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            margin: 20px;
        }

        .table {
            width: 600px;
            height: 400px;
            border: 2px solid #ccc;
            border-radius: 10px;
            background-color: #fff;
            position: relative;
            overflow: hidden;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .tool {
            width: 80px;
            height: 80px;
            cursor: grab;
            position: absolute;
        }

        .tool img {
            width: 100%;
            height: 100%;
            object-fit: contain;
        }

        .tool[data-tool="Scissors"] {
            top: 50px;
            left: 50px;
        }

        .tool[data-tool="Forceps"] {
            top: 50px;
            right: 50px;
        }

        .tool[data-tool="Scalpel"] {
            bottom: 50px;
            left: 50px;
        }

        .info {
            margin: 20px;
            font-size: 18px;
        }

        .controls {
            margin-top: 20px;
        }

        .counts {
            margin: 20px;
            font-size: 18px;
            font-weight: bold;
            text-align: center;
        }

        button {
            padding: 10px 15px;
            margin: 5px;
            font-size: 16px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: white;
        }

        button:hover {
            background-color: #0056b3;
        }

        select {
            padding: 10px;
            font-size: 16px;
            margin: 5px;
            border-radius: 5px;
        }

        .alert {
            color: red;
            font-weight: bold;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <h1>Smart Surgical Table</h1>
    <div class="table" id="table">
        <!-- Scissors -->
        <div class="tool" id="scissors" data-tool="Scissors">
            <img src="https://imocare-eg.com/wp-content/uploads/2022/08/scsior.jpg" alt="Scissors">
        </div>
        <!-- Forceps -->
        <div class="tool" id="forceps" data-tool="Forceps">
            <img src="https://sc04.alicdn.com/kf/A846c2945d90c4f69ab75b785d22a0832P/954691854/A846c2945d90c4f69ab75b785d22a0832P.jpg" alt="Forceps">
        </div>
        <!-- Scalpel -->
        <div class="tool" id="scalpel" data-tool="Scalpel">
            <img src="https://www.emedicshop.com/image/cache/catalog/Standard-Scalpel-600x424-1100x1100w.jpg" alt="Scalpel">
        </div>
    </div>
    <div class="info" id="info">Manage the tools below.</div>
    <div class="counts" id="counts">
        Scissors: 3<br>
        Forceps: 3<br>
        Scalpel: 3<br>
        Unsterilized Tools: 9
    </div>
    <div class="controls">
        <select id="toolSelector">
            <option value="Scissors">Scissors</option>
            <option value="Forceps">Forceps</option>
            <option value="Scalpel">Scalpel</option>
        </select>
        <button onclick="sterilizeSelectedTool()">Sterilize Selected Tool</button>
        <button onclick="decreaseSelectedTool()">Decrease Selected Tool</button>
        <button onclick="sterilizeTools()">Sterilize All Tools</button>
        <button onclick="resetTools()">Reset Tools</button>
    </div>
    <div class="alert" id="alert"></div>

    <script>
        // Tool counts
        const toolCounts = {
            Scissors: 3,
            Forceps: 3,
            Scalpel: 3,
        };

        let unsterilizedCount = 9;

        // Update the counts display
        function updateCountsDisplay() {
            const countsDisplay = document.getElementById("counts");
            countsDisplay.innerHTML = `
                Scissors: ${toolCounts.Scissors}<br>
                Forceps: ${toolCounts.Forceps}<br>
                Scalpel: ${toolCounts.Scalpel}<br>
                Unsterilized Tools: ${unsterilizedCount}
            `;
        }

        // Show alert if tool count is critically low
        function showAlert(toolName) {
            const alertBox = document.getElementById("alert");
            if (toolCounts[toolName] === 1) {
                alertBox.textContent = `⚠️ Warning: ${toolName} count is critically low!`;
            } else if (toolCounts[toolName] === 0) {
                alertBox.textContent = `❌ ${toolName} is out of stock!`;
            } else {
                alertBox.textContent = ""; // Clear alert if no issues
            }
        }

        // Decrease a selected tool
        function decreaseSelectedTool() {
            const selectedTool = document.getElementById("toolSelector").value;
            if (toolCounts[selectedTool] > 0) {
                toolCounts[selectedTool]--;
                unsterilizedCount--;
                updateCountsDisplay();
                showAlert(selectedTool);
                const info = document.getElementById("info");
                info.textContent = `You decreased ${selectedTool}. Remaining: ${toolCounts[selectedTool]}`;
            } else {
                const info = document.getElementById("info");
                info.textContent = `${selectedTool} is already at zero!`;
            }
        }

        // Sterilize a specific tool
        function sterilizeSelectedTool() {
            const selectedTool = document.getElementById("toolSelector").value;
            if (toolCounts[selectedTool] > 0 && unsterilizedCount > 0) {
                unsterilizedCount--;
                updateCountsDisplay();
                const info = document.getElementById("info");
                info.textContent = `You sterilized one ${selectedTool}. Remaining unsterilized tools: ${unsterilizedCount}`;
            } else {
                const info = document.getElementById("info");
                info.textContent = `No unsterilized ${selectedTool} to sterilize!`;
            }
        }

        // Sterilize all tools
        function sterilizeTools() {
            if (unsterilizedCount > 0) {
                unsterilizedCount = 0;
                updateCountsDisplay();
                const info = document.getElementById("info");
                info.textContent = "All tools have been sterilized!";
            } else {
                const info = document.getElementById("info");
                info.textContent = "All tools are already sterilized!";
            }
        }

        // Reset all tools to their initial counts
        function resetTools() {
            toolCounts.Scissors = 3;
            toolCounts.Forceps = 3;
            toolCounts.Scalpel = 3;
            unsterilizedCount = 9;
            updateCountsDisplay();
            const info = document.getElementById("info");
            info.textContent = "All tools have been reset.";
            document.getElementById("alert").textContent = ""; // Clear alert
        }

        // Initialize display
        updateCountsDisplay();
    </script>
</body>
</html>
